In [1]:
import pandas as pd
import numpy as np

In [21]:
# Reading deliveries file.

deliveries_df = pd.read_csv("data/deliveries.csv")
matches_df = pd.read_csv("data/matches.csv")

In [28]:
# First 5 rows

# deliveries_df.head()
# matches_df.head()


print(type(deliveries_df))

deliveries_df['inning']

<class 'pandas.core.frame.DataFrame'>

0         1
1         1
2         1
3         1
4         1
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
         ..
179048    2
179049    2
179050    2
179051    2
179052    2
179053    2
179054    2
179055    2
179056    2
179057    2
179058    2
179059    2
179060    2
179061    2
179062    2
179063    2
179064    2
179065    2
179066    2
179067    2
179068    2
179069    2
179070    2
179071    2
179072    2
179073    2
179074    2
179075    2
179076    2
179077    2
Name: inning, Length: 179078, dtype: int64

In [8]:
# Statistics describe of dataframe

# deliveries_df.describe()
# matches_df.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000

In [10]:
# dtypes 

# deliveries_df.dtypes
# matches_df.dtypes
# matches_df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [13]:
# info of a dataframe

# deliveries_df.info
# deliveries_df.info(verbose=False)
# deliveries_df.info()
# deliveries_df.info(memory_usage ='deep')
# matches_df.info(memory_usage ='deep')
# Category type - Advance concept.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Columns: 21 entries, match_id to fielder
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [15]:
# unique teams

# unique_teams = matches_df.team1.unique()
# print(np.sort(unique_teams))
# print(len(unique_teams))


# current_season_teams = matches_df[matches_df.season == 2019].team1.unique()
# print(np.sort(current_season_teams))
# print(len(current_season_teams))

['Chennai Super Kings' 'Delhi Capitals' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Mumbai Indians' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Sunrisers Hyderabad']
8

In [16]:
# sort name function

def alias(team):
    if team == 'Chennai Super Kings':
        return 'CSK'
    elif team == 'Deccan Chargers' or team == 'Sunrisers Hyderabad':
        return 'SRH'
    elif team == 'Delhi Capitals' or team == 'Delhi Daredevils':
        return 'DC'
    elif team == 'Gujarat Lions':
        return 'GL'
    elif team == 'Kings XI Punjab':
        return 'KXIP'
    elif team == 'Kochi Tuskers Kerala':
        return 'KTK'
    elif team == 'Kolkata Knight Riders':
        return 'KKR'
    elif team == 'Mumbai Indians':
        return 'MI'
    elif team == 'Pune Warriors' or team == 'Rising Pune Supergiants'or team == 'Rising Pune Supergiant':
        return 'RPSG'
    elif team == 'Rajasthan Royals':
        return 'RR'
    elif team == 'Royal Challengers Bangalore':
        return 'RCB'

In [22]:

# print(matches_df)

matches_df['team2']=matches_df['team2'].apply(alias)
matches_df['team1']=matches_df['team1'].apply(alias)
matches_df['winner']=list(map(alias,matches_df['winner']))
matches_df['toss_winner']=list(map(alias,matches_df['toss_winner']))

deliveries_df['batting_team'] = deliveries_df['batting_team'].apply(alias)
deliveries_df['bowling_team']=list(map(alias, deliveries_df['bowling_team']))

In [68]:
# deliveries_df
# matches_df

In [23]:
# # Match analysis.

print(f'No of mathces played - {matches_df.id.count()}')
print('Mathch results - ')
print(matches_df.result.value_counts())

No of mathces played - 756
Mathch results -
normal       743
tie            9
no result      4
Name: result, dtype: int64

In [24]:
print(f"Total venues - {matches_df['venue'].nunique()}")
np.sort(matches_df['venue'].unique())

Total venues - 41

array(['ACA-VDCA Stadium', 'Barabati Stadium', 'Brabourne Stadium',
       'Buffalo Park', 'De Beers Diamond Oval',
       'Dr DY Patil Sports Academy',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Dubai International Cricket Stadium', 'Eden Gardens',
       'Feroz Shah Kotla', 'Feroz Shah Kotla Ground', 'Green Park',
       'Himachal Pradesh Cricket Association Stadium',
       'Holkar Cricket Stadium', 'IS Bindra Stadium',
       'JSCA International Stadium Complex', 'Kingsmead',
       'M Chinnaswamy Stadium', 'M. A. Chidambaram Stadium',
       'M. Chinnaswamy Stadium', 'MA Chidambaram Stadium, Chepauk',
       'Maharashtra Cricket Association Stadium', 'Nehru Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal',
       'Rajiv Gandhi Intl. Cricket Stadium',
       'Sardar Patel Stadium, Motera',
       'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium',
       "St George's Park", 'Subrata Roy Sahara Stadium',
       'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha',
       'Wankhede Stadium'], dtype=object)

In [29]:
# Feroz Shah Kotla Ground == Feroz Shah Kotla

# IS Bindra Stadium = 'Punjab Cricket Association IS Bindra Stadium, Mohali', = 'Punjab Cricket Association Stadium, Mohali',

# 'M Chinnaswamy Stadium' ==    'M. Chinnaswamy Stadium',
# 'M. A. Chidambaram Stadium', == 'MA Chidambaram Stadium, Chepauk',

# 'Rajiv Gandhi International Stadium, Uppal', 'Rajiv Gandhi Intl. Cricket Stadium',


matches_df['venue']=matches_df['venue'].str.replace('Feroz Shah Kotla Ground','Feroz Shah Kotla')
matches_df['venue']=matches_df['venue'].str.replace('M. Chinnaswamy Stadium', 'M Chinnaswamy Stadium')
matches_df['venue']=matches_df['venue'].str.replace('M. A. Chidambaram Stadium', 'MA Chidambaram Stadium, Chepauk')
matches_df['venue']=matches_df['venue'].str.replace('Rajiv Gandhi Intl. Cricket Stadium', 
                                                    'Rajiv Gandhi International Stadium, Uppal')
matches_df['venue']=matches_df['venue'].str.replace('Punjab Cricket Association IS Bindra Stadium, Mohali', 
                                'Punjab Cricket Association Stadium, Mohali')

matches_df['venue']=matches_df['venue'].str.replace('IS Bindra Stadium', 
                                'Punjab Cricket Association Stadium, Mohali')


print(f"Total venues - {matches_df['venue'].nunique()}")
np.sort(matches_df['venue'].unique())

Total venues - 35

array(['ACA-VDCA Stadium', 'Barabati Stadium', 'Brabourne Stadium',
       'Buffalo Park', 'De Beers Diamond Oval',
       'Dr DY Patil Sports Academy',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Dubai International Cricket Stadium', 'Eden Gardens',
       'Feroz Shah Kotla', 'Green Park',
       'Himachal Pradesh Cricket Association Stadium',
       'Holkar Cricket Stadium', 'JSCA International Stadium Complex',
       'Kingsmead', 'M Chinnaswamy Stadium',
       'MA Chidambaram Stadium, Chepauk',
       'Maharashtra Cricket Association Stadium', 'Nehru Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Punjab Cricket Association Stadium, Mohali',
       'Rajiv Gandhi International Stadium, Uppal',
       'Sardar Patel Stadium, Motera',
       'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium',
       "St George's Park", 'Subrata Roy Sahara Stadium',
       'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha',
       'Wankhede Stadium'], dtype=object)

In [34]:
# Number of matches by venue

# matches_df['venue'].value_counts()
# matches_df['venue'].value_counts().head(10)
# matches_df['venue'].value_counts().tail()

In [35]:
ball_matches_merge=pd.merge(matches_df,deliveries_df,right_on='match_id',left_on='id')

In [36]:
ball_matches_merge[ball_matches_merge['batsman_runs'] ==6].groupby('venue').venue.agg('count').sort_values(ascending=False)

venue
M Chinnaswamy Stadium                                  1117
Wankhede Stadium                                        900
Eden Gardens                                            861
Feroz Shah Kotla                                        834
Rajiv Gandhi International Stadium, Uppal               660
MA Chidambaram Stadium, Chepauk                         609
Punjab Cricket Association Stadium, Mohali              526
Sawai Mansingh Stadium                                  363
Maharashtra Cricket Association Stadium                 261
Dr DY Patil Sports Academy                              173
Holkar Cricket Stadium                                  155
Subrata Roy Sahara Stadium                              141
Kingsmead                                               130
Sardar Patel Stadium, Motera                            130
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     129
SuperSport Park                                         120
Brabourne Stadium                                       114
Himachal Pradesh Cricket Association Stadium            108
Saurashtra Cricket Association Stadium                  104
JSCA International Stadium Complex                       76
Sharjah Cricket Stadium                                  76
Barabati Stadium                                         68
New Wanderers Stadium                                    64
Newlands                                                 63
St George's Park                                         62
Dubai International Cricket Stadium                      58
Shaheed Veer Narayan Singh International Stadium         44
Sheikh Zayed Stadium                                     40
Nehru Stadium                                            39
Green Park                                               36
De Beers Diamond Oval                                    34
Buffalo Park                                             27
Vidarbha Cricket Association Stadium, Jamtha             26
ACA-VDCA Stadium                                         25
OUTsurance Oval                                           8
Name: venue, dtype: int64

In [137]:
# ball_matches_merge.groupby(['venue','season', 'inning']).agg({'total_runs':'sum'})


# ball_matches_merge.groupby(['venue','season']).agg({'total_runs':'sum'}).sort_values(by=['season','total_runs'],ascending=False)

In [147]:
ball_matches_merge.groupby(['venue','season','dismissal_kind']).agg({'dismissal_kind':'count'}).sort_values(by=['season'],ascending=False)

                                                                     dismissal_kind
venue                                      season dismissal_kind
ACA-VDCA Stadium                           2019   bowled                          4
M Chinnaswamy Stadium                      2019   caught                         68
MA Chidambaram Stadium, Chepauk            2019   run out                         4
                                                  lbw                             3
                                                  caught                         65
                                                  bowled                         10
ACA-VDCA Stadium                           2019   caught                         20
M Chinnaswamy Stadium                      2019   stumped                         1
                                                  run out                         3
                                                  lbw                             3
                                                  bowled                          7
Eden Gardens                               2019   bowled                         11
Feroz Shah Kotla                           2019   stumped                         3
                                                  run out                         8
                                                  lbw                             6
                                                  caught                         59
                                                  bowled                         12
Eden Gardens                               2019   run out                         3
                                                  lbw                             6
                                                  hit wicket                      1
MA Chidambaram Stadium, Chepauk            2019   stumped                         7
Punjab Cricket Association Stadium, Mohali 2019   bowled                         13
                                                  caught                         47
                                                  lbw                             7
Wankhede Stadium                           2019   run out                         3
                                                  retired hurt                    1
                                                  lbw                             5
                                                  caught                         67
                                                  bowled                          4
Sawai Mansingh Stadium                     2019   stumped                         1
...                                                                             ...
Punjab Cricket Association Stadium, Mohali 2008   run out                         8
                                                  lbw                             6
                                                  hit wicket                      2
                                                  caught and bowled               4
                                                  caught                         40
                                                  bowled                         19
M Chinnaswamy Stadium                      2008   run out                        14
                                                  lbw                             6
                                                  caught                         53
                                                  bowled                         15
Wankhede Stadium                           2008   retired hurt                    1
                                                  lbw                             1
                                                  caught and bowled               5
                                                  caught                         46
                                                  bowled                          8
Dr DY Patil Sports Academy                 2008   lbw                             1
                                                  caught                         34
                                                  bowled                         11
Feroz Shah Kotla                           2008   bowled                         16
                                                  caught                         37
                                                  lbw                             1
                                                  run out                         7
                                                  stumped                         2
Sawai Mansingh Stadium                     2008   stumped                         2
                                                  run out                        13
                                                  lbw                             8
                                                  caught and bowled               6
                                                  caught                         40
                                                  bowled                         18
Dr DY Patil Sports Academy                 2008   run out                         3

[725 rows x 1 columns]